name: ðŸ“„âœ¨ Release CV

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build PDF
        run: |
          rm -rf build/ && mkdir -p build
          tectonic -X build 2> build/latex_errors.log || { cat build/latex_errors.log; exit 1; }

      - name: Find PDF
        run: |
          PDF_PATH=$(find build/ -type f -name "*.pdf" | head -n 1)
          [ -z "$PDF_PATH" ] && echo "No PDF found!" && exit 1
          echo "PDF_PATH=$PDF_PATH" >> $GITHUB_ENV

      - name: Tag & Release
        run: |
          TAG=$(date +%Y-%m-%d)
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag $TAG
          git push origin $TAG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.PDF_PATH }}
          tag_name: ${{ env.Tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
